// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquaresApp.Storage.Data;

namespace SquaresApp.Storage.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221022085720_AddPointsTable")]
    partial class AddPointsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            
            modelBuilder.Entity("SquaresApp.Storage.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Xaxis")
                        .HasColumnType("int");

                    b.Property<int>("Yaxis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

#pragma warning restore 612, 618
        }
    }
}
